# Generated by Django 4.0.6 on 2022-07-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_details',
            new_name='Order_detail',
        ),
    ]
